server:
  port: 8930
spring:
  application:
     name: shop-order
  shardingsphere:
    datasource:
      names: master0,master0slave,master1,master1slave
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.101.151.43:3306/shop-order?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
        username: zy
        password: 123456
      master0slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.101.151.43:3306/shop-order1?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
        username: zy
        password: 123456
      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.101.151.43:3306/shop-order2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
        username: zy
        password: 123456
      master1slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.101.151.43:3306/shop-order3?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
        username: zy
        password: 123456
    sharding:
      tables:
        shop_order:
          actual-data-nodes: ds$->{0..1}.shop_order_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: shop_order_$->{id % 2}
      default-database-strategy:
        standard:
          sharding-column: buyer_id
          precise-algorithm-class-name: top.zhouy.shoporder.config.MyPreciseShardingAlgorithm
      default-data-source-name: ds0
      master-slave-rules:
        ds0:
          master-data-source-name: master0
          slave-data-source-names: master0slave
        ds1:
          master-data-source-name: master1
          slave-data-source-names: master1slave
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.zhouy.top:8760/eureka/


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: top.zhouy.shoporder.bean.entity
  type-enums-package: top.zhouy.shoporder.bean.type

tx-lcn:
  client:
    manager-address: www.zhouy.top:9020
