server:
  port: 8760

spring:
  application:
    name: eurka-server

eureka:
  instance:
    hostname: zhouy.top
  server:
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/