server:
  port: 8780

spring:
  application:
    name: config-server
  cloud:
    label: master
    config:
      server:
        git:
          uri: https://github.com/zhouyanzy/zy-cloud.git
          searchPaths: respo
          username: zhouyanzy
          password: zhouyan1217

eureka:
  client:
    serviceUrl:
      defaultZone: http://zhouy.top:8760/eureka/