server:
  port: 8820
spring:
  application:
     name: blog-home
  datasource:
     url: jdbc:mysql://47.101.151.43:3306/dbblog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
     username: zy
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     druid:
       initial-size: 5  # 初始化大小
       min-idle: 5  # 最小
       max-active: 100  # 最大
       max-wait: 60000  # 配置获取连接等待超时的时间
       time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
       validationQuery: select 'x'
       test-while-idle: true  # 当连接空闲时，是否执行连接测试
       test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
       test-on-return: false  # 在连接归还到连接池时是否测试该连接
       filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
       poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
       maxPoolPreparedStatementPerConnectionSize: 20
       maxOpenPreparedStatements: 20
       # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
       connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
        # 合并多个DruidDataSource的监控数据
       #use-global-data-source-stat: true
       #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
       web-stat-filter:
           enabled: true #是否启用StatFilter默认值true
           url-pattern: /*
           exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
           session-stat-enable: true
           session-stat-max-count: 10
       #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
       stat-view-servlet:
           enabled: true #是否启用StatViewServlet默认值true
           url-pattern: /druid/*
           reset-enable: true
           login-username: admin
           login-password: admin
  redis:
    database: 1
    host: 47.101.151.43
    port: 6379
    password: zy1217
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://zhouy.top:8760/eureka/

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: top.zhouy.bloghome.bean.entity
  type-enums-package: top.zhouy.bloghome.bean.type
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty

security:
  oauth2:
    client:
      id: ${spring.application.name}
      client-id: blog
      client-secret: blog
      access-token-uri: http://zhouy.top:8790/oauth/token
      user-authorization-uri: http://zhouy.top:8790/oauth/authorize
      authentication-scheme: header
    resource:
      jwt:
        key-uri: http://zhouy.top:8790/oauth/token_key
      token-info-uri: http://zhouy.top:8790/oauth/check_token #检查令牌